add gh action

diff --git a/.github/workflows/deploy-storybook.yml b/.github/workflows/deploy-storybook.yml
--- a/.github/workflows/deploy-storybook.yml
+++ b/.github/workflows/deploy-storybook.yml
@@ -29,8 +29,8 @@ jobs:
       - name: Build Storybook
         run: npm run build-storybook
 
-      - name: Deploy to GitHub Pages
-        uses: actions/configure-pages@v3
+      - name: Check if build was successful
+        run: if [ ! -d "./storybook-static" ]; then echo "Build directory not found"; exit 1; fi
 
       - name: Upload artifact
         uses: actions/upload-artifact@v4
